package analyzer

// AnalysisPrompt is the comprehensive prompt for paper analysis
const AnalysisPrompt = `You are analyzing an AI/ML research paper for CS students. Your goal is to create a comprehensive, student-friendly analysis that will be converted into a LaTeX document.

IMPORTANT: Output ONLY the LaTeX document content. Do NOT include markdown formatting, code blocks, or explanations. Start directly with the LaTeX content.

Generate a complete LaTeX document following this structure:

\documentclass[11pt,a4paper]{article}

\usepackage[utf8]{inputenc}
\usepackage{amsmath,amssymb,amsfonts}
\usepackage{graphicx}
\usepackage{hyperref}
\usepackage{xcolor}
\usepackage{geometry}
\usepackage{tcolorbox}
\usepackage{enumitem}

\geometry{margin=1in}

\newtcolorbox{keyinsight}{
    colback=blue!5!white,
    colframe=blue!75!black,
    title=Key Insight
}

\newtcolorbox{prerequisite}{
    colback=green!5!white,
    colframe=green!75!black,
    title=Prerequisites
}

\title{[EXTRACT PAPER TITLE]: Student Guide}
\author{Generated by Research Paper Helper}
\date{\today}

\begin{document}

\maketitle
\tableofcontents
\newpage

\section{Executive Summary}
[Write 3-4 sentences explaining what this paper is about and why it matters]

\section{Problem Statement}
[Explain the specific problem this paper addresses, why it's important, and what the limitations of existing approaches are]

\section{Methods Overview}
[List the primary techniques/architectures used]
\begin{itemize}
\item [Method 1]
\item [Method 2]
\end{itemize}

\section{Detailed Methodology}

\subsection{Prerequisites}
\begin{prerequisite}
[List specific fundamental concepts needed - be specific, not vague like "linear algebra". Instead say things like "Understanding of matrix multiplication, eigenvalues, gradient descent, backpropagation, etc."]

Prior work that should be understood:
\begin{itemize}
\item [Specific paper or concept 1]
\item [Specific paper or concept 2]
\end{itemize}
\end{prerequisite}

\subsection{Architecture and Approach}
[Break down the methodology step-by-step. Explain mathematical formulations clearly. Use analogies where helpful. Define all notation explicitly.]

\subsection{Mathematical Formulations}
[Explain key equations with context. For example:]

The attention mechanism is computed as:
\begin{equation}
\text{Attention}(Q, K, V) = \text{softmax}\left(\frac{QK^T}{\sqrt{d_k}}\right)V
\end{equation}

[Explain what Q, K, V represent and why this formulation works]

\subsection{Implementation Details}
[Key algorithmic steps and design choices with rationale]

\section{The Breakthrough}
\begin{keyinsight}
[Explain the novel contribution - what is the "WOW moment"? What makes this approach better/different? Why is this work significant?]
\end{keyinsight}

\section{Experimental Setup}

\subsection{Datasets}
[List and briefly describe the benchmark datasets used]
\begin{itemize}
\item Dataset 1: [description]
\item Dataset 2: [description]
\end{itemize}

\subsection{Evaluation Metrics}
[Explain what metrics were used and why they matter]

\subsection{Baselines}
[What methods was this compared against?]

\section{Results and Improvements}

\subsection{Quantitative Results}
[Present specific numbers and improvements. For example: "Achieved 95.2\% accuracy compared to baseline 89.1\%, a 6.1 percentage point improvement"]

\subsection{Qualitative Improvements}
[Non-numerical benefits]

\subsection{Limitations}
[Where does the approach struggle? Be honest about limitations.]

\section{Conclusion and Impact}

\subsection{Key Takeaways}
\begin{itemize}
\item [Takeaway 1]
\item [Takeaway 2]
\item [Takeaway 3]
\end{itemize}

\subsection{Impact on the Field}
[How has this work influenced subsequent research?]

\subsection{Future Directions}
[What are the promising next steps?]

\end{document}

CRITICAL INSTRUCTIONS:
1. Write for CS students, not experts
2. Explain technical terms when first introduced
3. Be detailed but clear
4. Use examples where helpful
5. Maintain technical accuracy while being accessible
6. Output ONLY valid LaTeX - no markdown code blocks, no explanations before or after
7. Properly escape special LaTeX characters (%, $, &, #, _, {, }, ~, ^, \)
8. Be specific about prerequisites - don't say "linear algebra", say "matrix multiplication, eigenvectors, SVD"
9. Include specific numerical results where available
10. Make sure all LaTeX environments are properly closed

Generate the complete LaTeX document now:`

// MetadataExtractionPrompt is focused on just extracting basic info
const MetadataExtractionPrompt = `Extract the title from this research paper and provide it in this exact format:

TITLE: [exact paper title]

Be precise and extract the exact title as it appears in the paper.`

// ValidationPrompt checks the generated LaTeX
const ValidationPrompt = `Review this LaTeX code for syntax errors. Check:
1. All environments are properly opened and closed (\begin{} and \end{} match)
2. All special characters are properly escaped
3. All equations are properly formatted
4. No markdown syntax mixed in

LaTeX code to validate:
%s

If there are errors, output ONLY the corrected LaTeX code. If it's valid, output: VALID`
