package analyzer

// AnalysisPrompt is the main prompt for analyzing research papers
const AnalysisPrompt = `You are an expert AI/ML researcher and technical writer tasked with analyzing research papers for CS students.

Please analyze this research paper PDF and generate a comprehensive, student-friendly LaTeX document that explains the paper in detail.

The output should be a COMPLETE, READY-TO-COMPILE LaTeX document following this structure:

\documentclass[11pt,a4paper]{article}
\usepackage[utf8]{inputenc}
\usepackage{amsmath,amssymb,amsfonts}
\usepackage{graphicx}
\usepackage{hyperref}
\usepackage{xcolor}
\usepackage{geometry}
\usepackage{tcolorbox}
\usepackage{enumitem}
\geometry{margin=1in}

% Custom environments
\newtcolorbox{keyinsight}{
    colback=blue!5!white,
    colframe=blue!75!black,
    title=Key Insight
}

\newtcolorbox{prerequisite}{
    colback=green!5!white,
    colframe=green!75!black,
    title=Prerequisites
}

\title{[Paper Title]: Technical Report Student Guide}
\author{Generated by Research Paper Helper}
\date{\today}

\begin{document}

\maketitle
\tableofcontents
\newpage

\section{Executive Summary}
% 3-4 sentence overview: What is this paper about? Why does it matter?

\section{Problem Statement}
% What specific problem does this paper address?
% Why is this problem important?
% What are the limitations of existing approaches?

\section{Methods Overview}
% List the primary techniques/architectures used

\section{Detailed Methodology}

\subsection{Prerequisites}
\begin{prerequisite}
% Specific concepts needed (NOT vague like "linear algebra")
% Prior work/papers that should be understood first
\end{prerequisite}

\subsection{Architecture and Approach}
% Break down the methodology step-by-step
% Explain mathematical formulations clearly
% Use analogies where helpful
% Define all notation explicitly

\subsection{Implementation Details}
% Key algorithmic steps
% Design choices and rationale

\section{The Breakthrough}
\begin{keyinsight}
% What is the breakthrough/novel contribution?
% Why is this approach better/different?
% What makes this work significant?
\end{keyinsight}

\section{Experimental Setup}
\subsection{Datasets}
% Benchmark datasets used

\subsection{Evaluation Metrics}
% Metrics used for evaluation

\section{Results and Improvements}
% Quantitative improvements (with specific numbers)
% Qualitative improvements
% Where does it excel? Where are limitations?

\section{Conclusion}
% Key takeaways for students
% Impact on the field
% Future directions

\end{document}

IMPORTANT:
- Write for CS students, not experts
- Explain technical terms when first introduced
- Be detailed but clear
- Use examples where helpful
- Maintain technical accuracy while being accessible
- Output ONLY the complete LaTeX document, nothing else
- Do NOT include markdown code blocks or any other formatting
- Start directly with \documentclass

LATEX SYNTAX RULES (CRITICAL):
- ALWAYS use proper LaTeX command syntax with braces: \textit{word} NOT \textitword
- ALWAYS use proper LaTeX command syntax: \textbf{word} NOT \textbfword
- Use LaTeX math symbols inside $ or \[ \]: NOT Unicode symbols
- Escape special characters: \_ for underscore, \% for percent, \$ for dollar
- Use \times for multiplication, \in for element-of, NOT × or ∈
- Test every command has proper braces: \command{content}
- Math mode: Use $x \in R$ NOT $x ∈ R$
`

// ValidationPrompt is used to validate and fix LaTeX syntax
const ValidationPrompt = `You are a LaTeX expert. Review this LaTeX document and fix any syntax errors.

If the document is valid, respond with: VALID

If there are errors, output the CORRECTED LaTeX document (complete, not just the fixes).

Document to review:
%s

Output:`
