package analyzer

// AnalysisPrompt is the comprehensive prompt for paper analysis
const AnalysisPrompt = `You are analyzing an AI/ML research paper for CS students. Your goal is to create a comprehensive, student-friendly analysis that will be converted into a LaTeX document.

CRITICAL: Output ONLY the LaTeX document content. Do NOT include:
- Explanatory text before or after the LaTeX
- Markdown formatting or code blocks
- Comments about the document quality
- Any text that is not LaTeX code

Start immediately with \documentclass and end with \end{document}. No other text should be included.

Generate a complete LaTeX document following this structure:

\documentclass[11pt,a4paper]{article}

\usepackage[utf8]{inputenc}
\usepackage{amsmath,amssymb,amsfonts}
\usepackage{graphicx}
\usepackage{hyperref}
\usepackage{xcolor}
\usepackage{geometry}
\usepackage[breakable]{tcolorbox}
\usepackage{enumitem}

\geometry{margin=1in}

% Adding 'breakable' allows the box to break across pages if needed
\newtcolorbox{keyinsight}{
    colback=blue!5!white,
    colframe=blue!75!black,
    title=Key Insight,
    breakable
}

\newtcolorbox{prerequisite}{
    colback=green!5!white,
    colframe=green!75!black,
    title=Prerequisites,
    breakable
}

\title{[EXTRACT THE EXACT PAPER TITLE FROM THE PDF]: Student Guide}
\author{Generated by Research Paper Helper}
\date{\today}

\begin{document}

\maketitle
\tableofcontents
\newpage

\section{Executive Summary}
[Write 3-4 sentences explaining what this paper is about and why it matters. Write as a single, well-formed paragraph.]

\section{Problem Statement}
[Explain the specific problem this paper addresses, why it's important, and what the limitations of existing approaches are. Write as a single, well-formed paragraph.]

\section{Methods Overview}
[List the primary techniques/architectures used. Use a description list for clarity.]
\begin{description}
\item[Method 1:] Brief explanation.
\item[Method 2:] Brief explanation.
\end{description}

\section{Detailed Methodology}

\subsection{Prerequisites}
\begin{prerequisite}
To fully understand this paper, students should have a solid grasp of the following concepts:

% Use a description list for better formatting of term-definition pairs.
\begin{description}
\item[Convolutional Neural Networks (CNNs):] Understanding the basic architecture of CNNs, including convolutional layers, pooling layers, and fully connected layers.
\item[Backpropagation:] The algorithm used to train neural networks by calculating gradients and updating weights.
\item[Gradient Descent:] An optimization algorithm used to minimize the loss function of a neural network.
\end{description}

Prior work that should be understood:
\begin{description}
\item[AlexNet:] A seminal CNN architecture that demonstrated the power of deep learning for image classification.
\item[ResNet:] A CNN architecture that uses residual connections to enable training of very deep networks.
\end{description}
\end{prerequisite}

\subsection{Architecture and Approach}
[Break down the methodology step-by-step. Explain it as if you are teaching the concept to a student. Ensure explanations are written in full paragraphs to allow for natural text wrapping.]

\subsection{Mathematical Formulations}
[Explain key equations with context. For example:]

The depthwise separable convolution can be represented as follows:

Let $X$ be the input tensor of size $H \times W \times C$, where $H$ is the height, $W$ is the width, and $C$ is the number of channels.
\begin{enumerate}
    \item \textbf{Depthwise Convolution:} Applies a single filter to each input channel. The output $Y_{DW}$ is of size $H \times W \times C$.
    \item \textbf{Pointwise Convolution:} Applies a 1x1 convolution to the output of the depthwise convolution. The output $Y_{PW}$ is of size $H \times W \times C'$, where $C'$ is the number of output channels.
\end{enumerate}

[Explain what the variables represent and why this formulation is efficient.]

\subsection{Implementation Details}
[List key algorithmic steps and design choices with rationale using an itemize environment.]
\begin{itemize}
    \item \textbf{Datasets:} CIFAR-10, CIFAR-100, and Tiny ImageNet.
    \item \textbf{Training:} Models were trained for 50 epochs using NVIDIA Tesla P100 GPUs.
\end{itemize}

\section{The Breakthrough}
\begin{keyinsight}
[Explain the novel contribution. What is the "WOW moment"? Why is this work significant? CRITICAL: Write this as a single, cohesive paragraph. Do not use lists or manual line breaks. This will ensure the text wraps correctly inside the colored box.]
\end{keyinsight}

\section{Experimental Setup}

\subsection{Datasets}
[List and briefly describe the benchmark datasets used in a list.]
\begin{itemize}
\item \textbf{CIFAR-10:} A dataset of 60,000 32x32 color images in 10 classes.
\item \textbf{CIFAR-100:} Contains 100 classes with 600 images per class.
\end{itemize}

\subsection{Evaluation Metrics}
[Explain what metrics were used and why they matter.]

\subsection{Baselines}
[What methods was this compared against?]

\section{Results and Improvements}

\subsection{Quantitative Results}
[Present specific numbers and improvements in complete sentences for readability. For example: "On the CIFAR-10 dataset, EfficientNetV2-S achieved the highest accuracy (96.53\%), followed by ResNet18 (96.05\%)." This avoids fragmented output.]

\subsection{Qualitative Improvements}
[Describe the non-numerical benefits, such as model efficiency or broader applicability, in a paragraph.]

\subsection{Limitations}
[Where does the approach struggle? Be honest about limitations. Use a bulleted list for clarity.]
\begin{itemize}
    \item The study focuses on image classification and may not generalize to other tasks.
    \item Energy consumption of the models was not considered.
\end{itemize}

\section{Conclusion and Impact}

\subsection{Key Takeaways}
\begin{itemize}
\item There is a trade-off between accuracy, inference time, model size, and computational cost.
\item The optimal choice of architecture depends on the specific application requirements.
\item Transfer learning can significantly enhance model accuracy.
\end{itemize}

\subsection{Impact on the Field}
[How has this work influenced subsequent research? Write as a brief paragraph.]

\subsection{Future Directions}
[What are the promising next steps? Use a bulleted list.]
\begin{itemize}
    \item Exploring next-generation lightweight architectures.
    \item Testing models in real-world deployment scenarios.
\end{itemize}

\end{document}

CRITICAL INSTRUCTIONS:
1. Write for CS students, not experts.
2. Explain technical terms when first introduced.
3. Be detailed but clear.
4. Use examples where helpful.
5. Maintain technical accuracy while being accessible.
6. Output ONLY valid LaTeX - no markdown code blocks, no explanations before or after.
7. Properly escape special LaTeX characters (%, $, &, #, _, {, }, ~, ^, \).
8. Be specific about prerequisites and use description lists for them.
9. Write explanations in full, cohesive paragraphs to ensure proper text wrapping, especially inside the 'keyinsight' and 'prerequisite' boxes.
10. Make sure all LaTeX environments are properly closed.

Generate the complete LaTeX document now. Remember: Output ONLY the LaTeX code starting with \documentclass and ending with \end{document}. No explanations or other text.`

// MetadataExtractionPrompt is focused on just extracting basic info
const MetadataExtractionPrompt = `Extract the title from this research paper and provide it in this exact format:

TITLE: [exact paper title]

Be precise and extract the exact title as it appears in the paper.`

// ValidationPrompt checks the generated LaTeX
const ValidationPrompt = `Review this LaTeX code for syntax errors. Check:
1. All environments are properly opened and closed (\begin{} and \end{} match)
2. All special characters are properly escaped
3. All equations are properly formatted
4. No markdown syntax mixed in

LaTeX code to validate:
%s

If there are errors, output ONLY the corrected LaTeX code. If it's valid, output: VALID`